version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
  ollama:
    image: ollama/ollama:latest
    ports: 
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    
volumes:
  mongodb-data:
  ollama_models: